export const hubContent = {
  hero: {
    tagline: "Natureza, lazer e acolhimento",
    subtitle: "Um centro de lazer completo em Socorro-SP para toda a família",
    cta: "Fale conosco",
  },
  about: {
    title: "O Pitauá",
    text: [
      "Em meio às serras e à natureza exuberante de Socorro, o Pitauá é um centro de lazer completo pensado para quem busca descanso, diversão, gastronomia e contato com a natureza em um só lugar. Muito mais do que uma pousada, o espaço reúne restaurante, pesqueiro, hospedagem, piscina, mini fazenda e estrutura para eventos, proporcionando experiências para famílias, casais, grupos e visitantes de toda a região.",
      "No Pitauá, você pode aproveitar a tranquilidade do interior, saborear pratos especiais no restaurante, viver momentos de lazer no pesqueiro, descansar em acomodações confortáveis e celebrar ocasiões especiais em um ambiente cercado pelo verde e pela atmosfera acolhedora de Socorro-SP.",
      "Seja para passar o dia, se hospedar, pescar, realizar eventos, aproveitar a gastronomia local ou viver momentos em família, o Pitauá oferece uma experiência completa de lazer e turismo rural em Socorro.",
    ],
    stats: [
      { value: "15", label: "Quartos" },
      { value: "1", label: "Lago de Pesca" },
      { value: "4", label: "Frentes de Lazer" },
    ],
  },
  highlights: [
    { icon: "BedDouble", label: "Hospedagem" },
    { icon: "UtensilsCrossed", label: "Restaurante" },
    { icon: "Fish", label: "Pesca Esportiva" },
    { icon: "Trees", label: "Mini Fazenda" },
    { icon: "Baby", label: "Playground" },
    { icon: "PartyPopper", label: "Espaço para Eventos" },
  ],
  businesses: [
    {
      id: "pousada",
      title: "Pousada",
      description: "15 quartos, piscina e café da manhã incluso",
      href: "/pousada",
      image: "/images/hub/pousada-pitaua-socorro-sp.png",
      alt: "Pousada Pitauá em Socorro-SP",
      cta: "Reserve sua estadia",
    },
    {
      id: "gastronomia",
      title: "Restaurante",
      description: "Sabores do interior em ambiente acolhedor",
      href: "/gastronomia",
      image: "/images/hub/restaurante-pitaua-socorro-sp.jpg",
      alt: "Restaurante Pitauá em Socorro-SP",
      cta: "Conheça o restaurante",
    },
    {
      id: "pesqueiro",
      title: "Pesqueiro",
      description: "Pesca esportiva em contato com a natureza",
      href: "/pesqueiro",
      image: "/images/hub/pesqueiro-pitaua-socorro-sp.jpg",
      alt: "Dia de pescaria no Pesqueiro Pitauá em Socorro",
      cta: "Venha pescar",
    },
    {
      id: "eventos",
      title: "Eventos",
      description: "Celebre momentos especiais em plena natureza",
      href: "/eventos",
      image: "/images/hub/eventos-casamento-pitaua-socorro-sp.jpg",
      alt: "Eventos e casamentos no Pitauá em Socorro-SP",
      cta: "Solicite orçamento",
    },
  ],
};
