export const pousadaContent = {
  meta: {
    title: "Pousada Pitauá em Socorro-SP | Suítes, Piscina e Café da Manhã",
    description:
      "Reserve sua hospedagem na Pousada Pitauá em Socorro-SP. Suítes confortáveis, piscina, café da manhã, cozinha compartilhada e serviço de massagem. Natureza e acolhimento para toda a família.",
  },
  hero: {
    title: "Descanse em meio à natureza",
    subtitle:
      "A Pousada Pitauá oferece conforto, tranquilidade e lazer em Socorro-SP",
    cta: "Reserve sua hospedagem",
    imagePlaceholder:
      "IMAGEM HERO: Vista panorâmica da pousada com natureza ao fundo — foto de alta qualidade, horizontal, formato 16:9",
  },
  intro: {
    title: "Sua casa longe de casa",
    text: "Na Pousada Pitauá, cada detalhe foi pensado para proporcionar o descanso que você merece. Cinco opções de quartos para diferentes estilos de hospedagem, estrutura completa de lazer e a beleza natural de Socorro-SP como pano de fundo — sua estadia vai muito além do simples descanso, é uma experiência de reconexão com a natureza e com as pessoas que você ama.",
  },
  quartos: [
    {
      id: "suite-confort-premium",
      nome: "Suíte Confort Premium",
      descricao: "Nossa suíte mais completa: ambiente espaçoso, decoração refinada e amenidades premium para uma estadia memorável em Socorro-SP.",
      destaques: ["Cama king-size", "Hidromassagem", "2 Smart TVs", "Cafeteira Dolce Gusto"],
      amenidades: [
        "Ar-condicionado",
        "Frigobar",
        "2 Smart TVs",
        "Banheira de hidromassagem",
        "Cama de casal king size",
        "Cafeteira Dolce Gusto",
        "Varanda privativa",
        "Vaga de veículo na porta",
      ],
      capacidade: 2,
      exclusivoCasais: true,
      aceitaPet: false,
      precos: { semana: 850, finalSemana: 1150 },
      images: [
        "/images/pousada/suite-confort-premium/01.png",
        "/images/pousada/suite-confort-premium/02.png",
        "/images/pousada/suite-confort-premium/03.png",
        "/images/pousada/suite-confort-premium/04.png",
        "/images/pousada/suite-confort-premium/05.png",
      ],
    },
    {
      id: "suite-master",
      nome: "Suíte Master",
      descricao: "Suíte ampla e sofisticada, perfeita para casais que buscam privacidade, elegância e o conforto de um ambiente cuidadosamente decorado.",
      destaques: ["Hidromassagem", "Varanda privativa", "Vaga na porta", "Smart TV"],
      amenidades: [
        "Ar-condicionado",
        "Frigobar",
        "Smart TV",
        "Banheira de hidromassagem",
        "1 cama de casal",
        "1 cama de solteiro",
        "Varanda privativa",
        "Vaga de veículo na porta",
      ],
      capacidade: 4,
      exclusivoCasais: false,
      aceitaPet: true,
      precos: { semana: 465, finalSemana: 625 },
      images: [
        "/images/pousada/suite-master/01.png",
        "/images/pousada/suite-master/02.png",
        "/images/pousada/suite-master/03.png",
        "/images/pousada/suite-master/04.png",
        "/images/pousada/suite-master/05.png",
      ],
    },
    {
      id: "standard-hidro",
      nome: "Quarto Standard com Hidromassagem",
      descricao: "O conforto do Standard com o diferencial da hidromassagem — ideal para casais que querem momentos de relaxamento profundo.",
      destaques: ["Hidromassagem", "Smart TV", "Ar-condicionado", "Casal + bicama solteiro"],
      amenidades: [
        "Ar-condicionado",
        "Frigobar",
        "Smart TV",
        "Banheira de hidromassagem",
        "1 cama de casal",
        "1 bicama de solteiro",
      ],
      capacidade: 4,
      exclusivoCasais: false,
      aceitaPet: true,
      precos: { semana: 425, finalSemana: 595 },
      images: [
        "/images/pousada/standard-hidro/01.png",
        "/images/pousada/standard-hidro/02.png",
        "/images/pousada/standard-hidro/03.png",
        "/images/pousada/standard-hidro/04.png",
      ],
    },
    {
      id: "standard",
      nome: "Quarto Standard",
      descricao: "Quarto acolhedor com ar-condicionado, smart TV e camas para até 3 pessoas. Aceita pet — ideal para quem viaja com a família.",
      destaques: ["Smart TV", "Ar-condicionado", "Frigobar", "Casal + 1 solteiro"],
      amenidades: [
        "Ar-condicionado",
        "Frigobar",
        "Smart TV",
        "1 cama de casal",
        "1 cama de solteiro",
      ],
      capacidade: 3,
      exclusivoCasais: false,
      aceitaPet: true,
      precos: { semana: 345, finalSemana: 465 },
      images: [
        "/images/pousada/standard/01.jpg",
        "/images/pousada/standard/02.jpg",
        "/images/pousada/standard/03.jpg",
        "/images/pousada/standard/04.jpg",
        "/images/pousada/standard/05.jpg",
      ],
    },
    {
      id: "basic-room",
      nome: "Basic Room",
      descricao: "Quarto prático e funcional com ar-condicionado, smart TV e camas para até 3 pessoas. A escolha certa para quem busca o essencial com qualidade.",
      destaques: ["Smart TV", "Ar-condicionado", "Frigobar", "Casal + 1 solteiro"],
      amenidades: [
        "Ar-condicionado",
        "Frigobar",
        "Smart TV",
        "1 cama de casal",
        "1 cama de solteiro",
      ],
      capacidade: 3,
      exclusivoCasais: false,
      aceitaPet: false,
      precos: { semana: 345, finalSemana: 465 },
      images: [
        "/images/pousada/basic-room/01.png",
        "/images/pousada/basic-room/02.png",
        "/images/pousada/basic-room/03.png",
        "/images/pousada/basic-room/04.png",
        "/images/pousada/basic-room/05.png",
      ],
    },
  ],
  estrutura: [
    {
      icon: "Coffee",
      title: "Café da Manhã",
      description: "Comece o dia com um café da manhã caprichado, preparado com ingredientes frescos e o carinho da nossa cozinha.",
      cover: "/images/pousada/inclusos/cafe-da-manha/cover-v2.jpg" as string | null,
      gallery: [
        "/images/pousada/inclusos/cafe-da-manha/01.jpg",
        "/images/pousada/inclusos/cafe-da-manha/02.jpg",
        "/images/pousada/inclusos/cafe-da-manha/03.jpg",
        "/images/pousada/inclusos/cafe-da-manha/04.jpg",
        "/images/pousada/inclusos/cafe-da-manha/05.jpg",
        "/images/pousada/inclusos/cafe-da-manha/06.jpg",
        "/images/pousada/inclusos/cafe-da-manha/07.jpg",
        "/images/pousada/inclusos/cafe-da-manha/08.jpg",
        "/images/pousada/inclusos/cafe-da-manha/09.jpg",
        "/images/pousada/inclusos/cafe-da-manha/10.jpg",
        "/images/pousada/inclusos/cafe-da-manha/11.jpg",
        "/images/pousada/inclusos/cafe-da-manha/12.jpg",
        "/images/pousada/inclusos/cafe-da-manha/13.jpg",
        "/images/pousada/inclusos/cafe-da-manha/14.jpg",
        "/images/pousada/inclusos/cafe-da-manha/15.jpg",
        "/images/pousada/inclusos/cafe-da-manha/16.jpg",
        "/images/pousada/inclusos/cafe-da-manha/18.jpg",
        "/images/pousada/inclusos/cafe-da-manha/19.jpg",
        "/images/pousada/inclusos/cafe-da-manha/20.jpg",
        "/images/pousada/inclusos/cafe-da-manha/21.jpg",
      ] as string[],
    },
    {
      icon: "Waves",
      title: "Piscina",
      description: "Piscina ao ar livre para refrescar os dias quentes e relaxar em meio à natureza de Socorro-SP.",
      cover: "/images/pousada/inclusos/piscina/cover-v2.jpg" as string | null,
      gallery: [
        "/images/pousada/inclusos/piscina/01.jpg",
        "/images/pousada/inclusos/piscina/02.jpg",
        "/images/pousada/inclusos/piscina/03.jpg",
        "/images/pousada/inclusos/piscina/04.jpg",
        "/images/pousada/inclusos/piscina/05.jpg",
        "/images/pousada/inclusos/piscina/06.jpg",
        "/images/pousada/inclusos/piscina/07.jpg",
        "/images/pousada/inclusos/piscina/08.jpg",
        "/images/pousada/inclusos/piscina/09.jpg",
        "/images/pousada/inclusos/piscina/10.jpg",
        "/images/pousada/inclusos/piscina/11.jpg",
        "/images/pousada/inclusos/piscina/13.jpg",
        "/images/pousada/inclusos/piscina/14.jpg",
        "/images/pousada/inclusos/piscina/15.jpg",
        "/images/pousada/inclusos/piscina/18.jpg",
        "/images/pousada/inclusos/piscina/19.jpg",
        "/images/pousada/inclusos/piscina/20.jpg",
      ] as string[],
    },
    {
      icon: "Utensils",
      title: "Cozinha Compartilhada",
      description: "Espaço de cozinha de uso comum, perfeito para preparar refeições rápidas com a flexibilidade de quem está em casa.",
      cover: "/images/pousada/inclusos/cozinha-compartilhada/cover.png" as string | null,
      gallery: [
        "/images/pousada/inclusos/cozinha-compartilhada/01.png",
        "/images/pousada/inclusos/cozinha-compartilhada/02.png",
        "/images/pousada/inclusos/cozinha-compartilhada/03.png",
        "/images/pousada/inclusos/cozinha-compartilhada/04.png",
      ] as string[],
    },
  ],
  servicos: [
    {
      icon: "Sparkles",
      title: "Massagem",
      description: "Serviço de massagem disponível mediante agendamento — complemente o relaxamento da sua estadia com um cuidado especial.",
      cover: "/images/pousada/inclusos/massagem/cover-v3.png" as string | null,
      gallery: [
        "/images/pousada/inclusos/massagem/01.jpg",
        "/images/pousada/inclusos/massagem/02.jpg",
        "/images/pousada/inclusos/massagem/03.jpg",
        "/images/pousada/inclusos/massagem/04.jpg",
        "/images/pousada/inclusos/massagem/05.jpg",
        "/images/pousada/inclusos/massagem/06.jpg",
        "/images/pousada/inclusos/massagem/07.png",
        "/images/pousada/inclusos/massagem/08.png",
      ] as string[],
    },
  ],
  experiencias: [
    {
      title: "Paz e Silêncio",
      description: "Socorro-SP é conhecida como a Cidade das Águas. A pousada está inserida num ambiente de muita natureza e tranquilidade, ideal para quem quer descanso real.",
      image: {
        src: "/images/pousada/experiencias/paz-e-silencio.jpg",
        alt: "Pousada Pitauá em Socorro-SP com piscina ao ar livre cercada por natureza",
      },
    },
    {
      title: "Sabores e Encontros",
      description: "Café da manhã caprichado, cozinha compartilhada para momentos práticos e o restaurante do Pitauá pertinho — a hospedagem que respeita seu ritmo e seus encontros.",
      image: {
        src: "/images/pousada/experiencias/sabores-e-encontros.jpg",
        alt: "Café da manhã servido na Pousada Pitauá em Socorro-SP",
      },
    },
    {
      title: "Socorro-SP a Poucos Minutos",
      description: "Localize-se estrategicamente para explorar as atrações da região: cachoeiras, trilhas, lojas de artesanato e todo o charme da Serra da Mantiqueira.",
      image: {
        src: "/images/pousada/experiencias/socorro-sp.jpg",
        alt: "Pitauá Centro de Lazer em Socorro-SP",
      },
    },
  ],
  faq: [
    {
      pergunta: "O café da manhã está incluso na diária?",
      resposta: "Sim! O café da manhã está incluso em todas as diárias da Pousada Pitauá, servido diariamente com opções variadas.",
    },
    {
      pergunta: "Posso levar animais de estimação?",
      resposta: "Animais de estimação são aceitos mediante consulta prévia e podem estar sujeitos a uma taxa adicional. Entre em contato pelo WhatsApp para confirmar.",
    },
    {
      pergunta: "Qual é o horário de check-in e check-out?",
      resposta: "O check-in é a partir das 14h e o check-out até as 12h. Horários especiais podem ser solicitados com antecedência, sujeitos à disponibilidade.",
    },
    {
      pergunta: "A pousada tem piscina?",
      resposta: "Sim! Temos piscina disponível para todos os hóspedes.",
    },
    {
      pergunta: "Posso usar a cozinha?",
      resposta: "Sim! A pousada conta com uma cozinha compartilhada de uso comum, ideal para refeições rápidas e momentos práticos durante a estadia.",
    },
    {
      pergunta: "Como faço uma reserva?",
      resposta: "Você pode reservar online em poucos minutos pelo nosso sistema de reservas. Clique em 'Reserve sua hospedagem' para conferir disponibilidade e finalizar suas datas. Se preferir falar com a gente antes, fale conosco pelo WhatsApp.",
    },
    {
      pergunta: "A pousada oferece serviço de massagem?",
      resposta: "Sim! Oferecemos serviço de massagem mediante agendamento. Consulte disponibilidade e valores pelo WhatsApp.",
    },
    {
      pergunta: "Há espaço de estacionamento?",
      resposta: "Sim, temos estacionamento gratuito para todos os hóspedes.",
    },
    {
      pergunta: "A pousada fica próxima ao centro de Socorro?",
      resposta: "A pousada fica a poucos minutos do centro de Socorro-SP, com fácil acesso às atrações da cidade e da região.",
    },
  ],
};
